# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Overview
    output: web, pdf
    folderitems:
    - title: Product 1 Overview
      url: /p1_landing_page.html
      output: web

    - title: Use Cases
      url: /p1_sample1.html
      output: web, pdf

  - title: Getting Started
    output: web, pdf

    folderitems:
    - title: Authorization
      url: /p1_sample4.html
      output: web, pdf

    - title: Access Tokens
      url: /p1_sample5.html
      output: web, pdf

    - title: Security
      url: /p1_sample6.html
      output: web, pdf

    - title: Best Practices
      url: /p1_sample7.html
      output: web, pdf

  - title: Tutorials
    output: web, pdf

    folderitems:
    - title: Sending a Message
      url: /p1_sample4.html
      output: web, pdf

    - title: Customizing User Experience
      url: /p1_sample5.html
      output: web, pdf

    - title: Integrating AI
      url: /p1_sample6.html
      output: web, pdf

    - title: Making Payments
      url: /p1_sample7.html
      output: web, pdf

  - title: SDKs
    output: web, pdf

    folderitems:
    - title: iOS
      url: /p1_sample4.html
      output: web, pdf

    - title: Android
      url: /p1_sample5.html
      output: web, pdf

    - title: JavaScript
      url: /p1_sample6.html
      output: web, pdf

    - title: Server-Side
      url: /p1_sample7.html
      output: web, pdf

  - title: API Reference
    output: web, pdf

    folderitems:
    - title: Pet
      url: /p1_sample4.html
      output: web, pdf

    - title: Store
      url: /p1_sample5.html
      output: web, pdf

    - title: User
      url: /p1_sample6.html
      output: web, pdf

  - title: Migration Guide
    output: web, pdf

    folderitems:
    - title: Migration Guide
      url: /p1_sample4.html
      output: web, pdf

  - title: Glossary
    output: web, pdf

    folderitems:
    - title: Glossary
      url: /p1_sample4.html
      output: web, pdf

  - title: Changelog
    output: web, pdf

    folderitems:
    - title: Changelog
      url: /p1_sample4.html
      output: web, pdf